spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springDemo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: Gah6kuP7ohfio4
  security:
    remember-me:
      key: blurooo